[package]
name = "pale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "src/lib/lib.rs"
test = true

[[bin]]
name = "pale"
path = "src/bin/main.rs"
